[RHPAM-3330-str] Operator/Image support for Kie-Server Cluster support
kiegroup/kie-cloud-operator pull request #613
Opened 2021-03-15 09:16 UTC by desmax74

PR to test console-cr-form with jbpm as a string in a dropdown list

2021-03-15 14:45 UTC, tchughesiv requested changes

2021-03-15 14:45 UTC, tchughesiv commented on pkg/apis/app/v2/kieapp_types.go
> +	JbpmCluster string `json:"jbpmCluster,omitempty"`
shouldn't this be a bool instead?

2021-03-15 14:45 UTC, tchughesiv commented on config/7.11.0/common.yaml
> +                      value: "true"
if this is set statically to true, how would the user change to false? maybe this needs to be a template var instead?
`[[.JbpmCluster]]` ?

2021-03-15 14:45 UTC, tchughesiv commented on pkg/controller/kieapp/defaults/defaults.go
> +			if len(cr.Spec.Objects.Servers) != 0 {
at this point in the code, in this servers loop, we already know len is not 0. are we sure this check is necessary?

2021-03-17 10:54 UTC, desmax74 commented
@tchughesiv thanks for the review but this was just for a test with swati

2021-03-17 11:13 UTC, closed without merging