[RHPAM-4115] Missing routes/custom-host permision for BA Operator
kiegroup/kie-cloud-operator pull request #722
Opened 2022-01-11 14:08 UTC by desmax74

See: https://issues.redhat.com/browse/RHPAM-4115
Signed-off-by: desmax74 <mdessi@redhat.com>

2022-01-11 14:09 UTC, desmax74 commented
@spolti @jakubschwan

2022-01-11 17:01 UTC, jakubschwan requested changes
please also re-generate csv files and add change done in all of these files, so updates are correctly visible in all places.

2022-01-12 13:17 UTC, jakubschwan approved these changes

2022-01-12 14:54 UTC, spolti commented
/approve
/lgtm

2022-01-12 14:56 UTC, merged