WIP [KIECLOUD-605] In Operator use Kie Server's RHDM mode
kiegroup/kie-cloud-operator pull request #752
Opened 2022-03-15 12:05 UTC by davidesalerno

Signed-off-by: Davide Salerno <dsalerno@redhat.com>

2022-03-16 10:38 UTC, davidesalerno commented on pkg/apis/app/v2/kieapp_types.go
> +	DecisionsOnly bool `json:"decisionsOnly,omitempty"`
@spolti thanks for the suggestion, I think that since we can remove the if logic from the common.yaml it is a good way to go .

2022-03-17 17:03 UTC, spolti commented on deploy/ui/form.json
> +                  "label": "Execute Kie Server with Decisions only capabilities",
```suggestion
                  "label": "Execute Kie Server only with Decisions capabilities",
```

2022-03-17 17:05 UTC, spolti requested changes

2022-03-17 17:05 UTC, spolti commented on pkg/controller/kieapp/defaults/defaults_test.go
> +	for _, env := range env.Servers[0].DeploymentConfigs[0].Spec.Template.Spec.Containers[0].Env {
there is abetter way to check for envs, e.g.:
```
assert.Equal(t, "InfinispanUser", getEnvVariable(env.Console.DeploymentConfigs[0].Spec.Template.Spec.Containers[0], "APPFORMER_INFINISPAN_USERNAME"))
```

2022-03-17 17:05 UTC, spolti commented on rhpam-config/7.13.0/common.yaml
> +                  ## DECISION ONLY MODE
can be removed.

2022-03-17 18:02 UTC, spolti commented
The final changes to correctly configure the rhdm decisionsOnly will be done on another PR after https://github.com/kiegroup/kie-cloud-operator/pull/751 is merged.

2022-03-17 18:02 UTC, spolti commented
/lgtm
/approve

2022-03-17 18:04 UTC, merged