[7.13.x] bump bundle version to 7.12.1-3
kiegroup/kie-cloud-operator pull request #782
Opened 2022-05-04 10:08 UTC by desmax74

bump bundle version to 7.12.1-3
Signed-off-by: desmax74 <mdessi@redhat.com>

2022-05-04 10:13 UTC, desmax74 commented
/ @jakubschwan

2022-05-04 11:51 UTC, davidesalerno approved these changes

2022-05-04 13:18 UTC, jakubschwan requested changes
Missing changes for version.go and version replace in 7.13.0 csv file. Please update the version go and re-generate the bundle related files.

2022-05-05 15:48 UTC, jakubschwan approved these changes
lgtm

2022-05-05 15:52 UTC, merged