[RHPAM-4404] KieApp missing description for terminationRoute property
kiegroup/kie-cloud-operator pull request #796
Opened 2022-06-16 08:09 UTC by desmax74

Signed-off-by: desmax74 <mdessi@redhat.com>
See:https://issues.redhat.com/browse/RHPAM-4404

2022-06-16 12:43 UTC, davidesalerno approved these changes

2022-06-17 14:28 UTC, spolti requested changes

2022-06-17 14:28 UTC, spolti commented on pkg/apis/app/v2/kieapp_types.go
> +// TerminationRoute configuration for the routes in the Workbench, KieServer, Dashbuilder,SmartRouter, Pim
```suggestion
// TerminationRoute configuration of the routes used by RHPAM components
```

2022-06-20 12:32 UTC, desmax74 commented
@spolti on the main https://github.com/kiegroup/kie-cloud-operator/pull/798

2022-06-20 13:14 UTC, spolti commented
/lgtm

2022-06-20 13:15 UTC, spolti commented
/lgtm cancel

2022-06-20 13:54 UTC, spolti commented
/lgtm

2022-06-20 13:57 UTC, merged