[RHPAM-4439] Vulnerable Version Of PostgreSQL Found
kiegroup/kie-cloud-operator pull request #810
Opened 2022-07-21 16:21 UTC by desmax74

Signed-off-by: desmax74 <mdessi@redhat.com>
See: https://issues.redhat.com/browse/RHPAM-4439

2022-08-05 13:31 UTC, spolti requested changes

2022-08-05 13:31 UTC, spolti commented on pkg/controller/kieapp/constants/constants.go
> +	//	PostgreSQLComponent: PostgreSQL12Component,
see my review on the first PR

2022-08-23 12:33 UTC, desmax74 commented on pkg/controller/kieapp/constants/constants.go
> +	//	PostgreSQLComponent: PostgreSQL12Component,
fixed

2022-08-23 13:16 UTC, spolti approved these changes

2022-08-23 15:02 UTC, spolti commented
/lgtm

2022-08-23 15:07 UTC, davidesalerno approved these changes

2022-08-23 15:23 UTC, merged